### ISSUE TITLE
Error: Malformed calls from JS: field sizes are different.

### ISSUE THREAD

**Issue by redefinered** [sueLan/react-native-anchor-point#3]
Hi,

This is super useful, thanks for the effort!

I'm running into an error, though. I am not sure what I am missing. Please refer to the following screenshots

actual error
![image](https://user-images.githubusercontent.com/5173630/105190253-c553cb80-5b70-11eb-9532-6b23f73654f1.png)

code
![image](https://user-images.githubusercontent.com/5173630/105190697-3bf0c900-5b71-11eb-9d7f-e291d680dfff.png)

Help me please? :(

**Comment by sueLan** [comment]
hi, better to use specific figure for WIDTH and HEIGHT

**Comment by redefinered** [comment]
oh so that's it. thanks! I ended up doing the transformation myself. thanks anyway ❤️
